### ISSUE TITLE
Color management

### ISSUE THREAD

**Issue by CRC-PSV** [rawgraphs/rawgraphs-app#243]
[ ] 1. Load your data
[ ] 2. Choose a chart
[ ] 3. Mapping
[ X] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**
Changing colors manually is painful when you get a lot of colors...

**Describe the solution you'd like**
I'd like to be able to import my Hexa-color numbers easily, so that my graphs in Rawgraphs use the same color pallette than elsewhere.
Or simply copy/paste a column of hexa-colors

**Comment by mikima** [comment]
We thought about it but since in a visualization doesn't make really sense to use more than 10 colors we decided that it's not that much complex, considering the fact that now you can save the project file and you have to insert colors just once.
If you notice in the new version just the first 10 colors are assigned, and if you have more values they are set as gray.

Anyway if this will become a popular request we can consider to handle it. To be consistent I think we should add a color datatype, otherwise just one wrong line would 'break' the chart.
